#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Push(i64),
    Duplicate,
    Swap,
    Discard,
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Store,
    Retrieve,
    Label(String),
    Call(String),
    Jump(String),
    JumpIfZero(String),
    JumpIfNegative(String),
    Return,
    End,
    OutputChar,
    OutputNumber,
    ReadChar,
    ReadNumber,
}
